/**
 * Generates supabase/seed.sql from the TypeScript seed data in lib/data/*.
 * The same data powers "demo mode" (no database), so the website looks
 * identical before and after you connect Supabase.
 *
 *   npm run seed:sql        → writes supabase/seed.sql
 *   supabase db reset       → applies migrations + seed.sql locally
 *
 * Rates are a SAMPLE derived from baseline mid-market rates + each provider's
 * typical pricing profile. Replace them with real data (or let the
 * /api/cron/update-rates job refresh them) before launch.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { SERVICES } from '../lib/data/services';
import { CORRIDORS, BASELINE_MID_MARKET } from '../lib/data/corridors';
import { buildRates } from '../lib/data/rates';
import { FAQS } from '../lib/data/faqs';
import { BLOG_POSTS } from '../lib/data/blog';
import { REVIEWS } from '../lib/data/reviews';
import { buildDemoHistory } from '../lib/data/history';

type Row = Record<string, unknown>;

function lit(v: unknown): string {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (Array.isArray(v)) return `ARRAY[${v.map((x) => lit(x)).join(',')}]::text[]`;
  if (v instanceof Date) return `'${v.toISOString()}'`;
  return `'${String(v).replace(/'/g, "''")}'`;
}

function insert(table: string, rows: Row[], columns: string[], conflict: string): string {
  if (rows.length === 0) return `-- ${table}: no rows\n`;
  const values = rows.map((r) => `  (${columns.map((c) => lit(r[c])).join(', ')})`).join(',\n');
  const updates = columns
    .filter((c) => c !== 'id')
    .map((c) => `${c} = excluded.${c}`)
    .join(', ');
  return `insert into public.${table} (${columns.join(', ')}) values\n${values}\non conflict (${conflict}) do update set ${updates};\n`;
}

function main() {
  const now = new Date().toISOString();
  const parts: string[] = [];
  parts.push(`-- Generated by scripts/generate-seed-sql.ts on ${now}\n-- Do not edit by hand; edit lib/data/* and re-run \`npm run seed:sql\`.\n`);
  parts.push('begin;\n');

  parts.push(
    insert(
      'services',
      SERVICES as unknown as Row[],
      [
        'id', 'name', 'name_ar', 'slug', 'logo_url', 'website_url', 'affiliate_url', 'affiliate_id', 'description', 'description_ar',
        'rating', 'total_reviews', 'is_active', 'is_featured', 'founded_year', 'headquarters', 'headquarters_ar', 'license_info', 'license_info_ar',
        'payout_methods', 'send_methods', 'supported_corridors', 'min_rating_to_show', 'priority_order', 'pros', 'pros_ar', 'cons', 'cons_ar', 'brand_color',
      ],
      'id',
    ),
  );

  parts.push(
    insert(
      'corridors',
      CORRIDORS as unknown as Row[],
      [
        'id', 'send_currency', 'receive_currency', 'send_country', 'send_country_ar', 'send_country_code', 'receive_country', 'receive_country_ar', 'receive_country_code',
        'flag_emoji', 'is_active', 'popularity_rank', 'monthly_search_volume', 'seo_title', 'seo_title_ar', 'seo_description', 'seo_description_ar',
        'currency_name', 'currency_name_ar', 'currency_symbol',
      ],
      'id',
    ),
  );

  const rates = buildRates(BASELINE_MID_MARKET, now);
  parts.push(
    insert(
      'rates',
      rates as unknown as Row[],
      [
        'id', 'service_id', 'corridor_id', 'exchange_rate', 'mid_market_rate', 'markup_percent', 'fixed_fee', 'fee_currency', 'percent_fee',
        'min_send_amount', 'max_send_amount', 'transfer_speed', 'transfer_speed_minutes', 'payout_method', 'promo_active', 'promo_text', 'promo_text_ar',
        'last_verified_at', 'verified_by', 'source', 'is_active',
      ],
      'service_id, corridor_id',
    ),
  );

  // 30 days of daily history per service × corridor so charts have data on day one.
  const history: Row[] = [];
  for (const r of rates) {
    const corridor = CORRIDORS.find((c) => c.id === r.corridor_id);
    if (!corridor) continue;
    for (const p of buildDemoHistory(corridor.send_currency, 30, r.mid_market_rate, r.markup_percent, 1)) {
      history.push({ service_id: r.service_id, corridor_id: r.corridor_id, exchange_rate: p.exchange_rate, mid_market_rate: p.mid_market_rate, recorded_at: p.recorded_at });
    }
  }
  const histCols = ['service_id', 'corridor_id', 'exchange_rate', 'mid_market_rate', 'recorded_at'];
  parts.push(`delete from public.rate_history where recorded_at >= now() - interval '31 days';\n`);
  for (let i = 0; i < history.length; i += 500) {
    const chunk = history.slice(i, i + 500);
    parts.push(`insert into public.rate_history (${histCols.join(', ')}) values\n${chunk.map((r) => `  (${histCols.map((c) => lit(r[c])).join(', ')})`).join(',\n')};\n`);
  }

  parts.push(insert('faqs', FAQS as unknown as Row[], ['id', 'question', 'question_ar', 'answer', 'answer_ar', 'category', 'corridor_id', 'service_id', 'sort_order', 'is_active'], 'id'));

  parts.push(
    insert(
      'blog_posts',
      BLOG_POSTS as unknown as Row[],
      ['id', 'slug', 'title', 'title_ar', 'excerpt', 'excerpt_ar', 'content', 'content_ar', 'featured_image', 'category', 'tags', 'author_name', 'is_published', 'published_at', 'seo_title', 'seo_description', 'views', 'reading_minutes'],
      'id',
    ),
  );

  parts.push(
    insert(
      'reviews',
      REVIEWS.map((r) => ({ ...r, user_id: null })) as unknown as Row[],
      ['id', 'user_id', 'service_id', 'corridor_id', 'rating', 'title', 'title_ar', 'body', 'body_ar', 'amount_sent', 'amount_received', 'send_currency', 'receive_currency', 'reported_rate', 'transfer_speed_actual', 'would_recommend', 'author_name', 'is_verified', 'is_approved', 'helpful_count', 'created_at'],
      'id',
    ),
  );

  parts.push('commit;\n');

  const out = join(__dirname, '..', 'supabase', 'seed.sql');
  mkdirSync(join(__dirname, '..', 'supabase'), { recursive: true });
  writeFileSync(out, parts.join('\n'));
  console.log(`wrote ${out}: ${SERVICES.length} services, ${CORRIDORS.length} corridors, ${rates.length} rates, ${history.length} history points, ${FAQS.length} faqs, ${BLOG_POSTS.length} posts, ${REVIEWS.length} reviews`);
}

main();
